In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [5]:
A = np.random.randn(10)
A

array([-0.69778768,  0.13238111,  0.50011739, -0.30627022,  0.91406494,
        1.19610789,  1.51001271,  0.32974388, -0.10251951,  0.01655901])

In [7]:
B = np.random.randn(10)
B

array([ 1.78383355,  1.2886605 ,  1.63115381, -1.97342664, -0.114518  ,
        0.96109753, -1.10235806,  1.10732325,  0.60579205,  1.80716325])

In [8]:
# Binary Functions
np.add(A,B)

array([ 1.08604586,  1.42104162,  2.1312712 , -2.27969686,  0.79954694,
        2.15720542,  0.40765465,  1.43706713,  0.50327254,  1.82372226])

In [10]:
np.maximum(A,B)

array([ 1.78383355,  1.2886605 ,  1.63115381, -0.30627022,  0.91406494,
        1.19610789,  1.51001271,  1.10732325,  0.60579205,  1.80716325])

In [12]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True